/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_appwindow (void);
GtkWidget* create_aboutwindow (void);
GtkWidget* create_txfileselection (void);
GtkWidget* create_wfpopupmenu (void);
GtkWidget* create_confdialog (void);
GtkWidget* create_macroconfigdialog (void);
GtkWidget* create_picwindow (void);
GtkWidget* create_txpicfileselection (void);
GtkWidget* create_rxpicfileselection (void);
GtkWidget* create_druidwindow (void);
